# Generated by Django 5.2 on 2025-04-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0003_altitudes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altitudes',
            options={'verbose_name': 'Altitude', 'verbose_name_plural': 'Altitudes'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='pressures',
            options={'verbose_name': 'Pression', 'verbose_name_plural': 'Pressions'},
        ),
        migrations.AlterModelOptions(
            name='temperatures',
            options={'verbose_name': 'Temperature', 'verbose_name_plural': 'Temperatures'},
        ),
        migrations.AddField(
            model_name='devices',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='lastSeenAt',
            field=models.DateTimeField(),
        ),
    ]
